# Generated by Django 2.2.7 on 2019-12-08 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BagCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_number', models.IntegerField(blank=True, null=True)),
                ('route', models.CharField(blank=True, max_length=128, null=True)),
                ('locality', models.CharField(blank=True, max_length=64, null=True)),
                ('administrative_area_level_1', models.CharField(blank=True, max_length=2, null=True)),
                ('country', models.CharField(blank=True, max_length=64, null=True)),
                ('postal_code', models.IntegerField(blank=True, null=True)),
                ('lat', models.DecimalField(decimal_places=12, default=0.0, max_digits=16)),
                ('lng', models.DecimalField(decimal_places=12, default=0.0, max_digits=16)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='locale', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BagRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='owner_request', to=settings.AUTH_USER_MODEL)),
                ('requestor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lbs', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('category', models.ManyToManyField(related_name='bags', to='donate.BagCategory')),
                ('request', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bag_req', to='donate.BagRequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bags', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
